language: go

go:
  - 1.4

before_script:
  - "source /etc/lsb-release && echo \"deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main\" | sudo tee /etc/apt/sources.list.d/rethinkdb.list"
  - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo apt-get update -q
  - sudo apt-get install rethinkdb
  - sudo rethinkdb --daemon
  - cp utils/config.go.example utils/config.go

# before_install:
#   - go get github.com/axw/gocov/gocov
#   - go get github.com/mattn/goveralls
#   - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
# script:
#   - $HOME/gopath/bin/goveralls -service=travis-ci